In [1]:
import pandas as pd
import datetime

In [2]:
jan = pd.read_csv('monthly_data/201901-citibike-tripdata.csv')
feb = pd.read_csv('monthly_data/201902-citibike-tripdata.csv')
mar = pd.read_csv('monthly_data/201903-citibike-tripdata.csv')
apr = pd.read_csv('monthly_data/201904-citibike-tripdata.csv')
may = pd.read_csv('monthly_data/201905-citibike-tripdata.csv')
jun = pd.read_csv('monthly_data/201906-citibike-tripdata.csv')
jul = pd.read_csv('monthly_data/201907-citibike-tripdata.csv')
aug = pd.read_csv('monthly_data/201908-citibike-tripdata.csv')
sep = pd.read_csv('monthly_data/201909-citibike-tripdata.csv')
oct = pd.read_csv('monthly_data/201910-citibike-tripdata.csv')
nov = pd.read_csv('monthly_data/201911-citibike-tripdata.csv')
dec = pd.read_csv('monthly_data/201912-citibike-tripdata.csv')

In [3]:
jan.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,320,2019-01-01 00:01:47.4010,2019-01-01 00:07:07.5810,3160.0,Central Park West & W 76 St,40.778968,-73.973747,3283.0,W 89 St & Columbus Ave,40.788221,-73.970416,15839,Subscriber,1971,1
1,316,2019-01-01 00:04:43.7360,2019-01-01 00:10:00.6080,519.0,Pershing Square North,40.751873,-73.977706,518.0,E 39 St & 2 Ave,40.747804,-73.973442,32723,Subscriber,1964,1
2,591,2019-01-01 00:06:03.9970,2019-01-01 00:15:55.4380,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3154.0,E 77 St & 3 Ave,40.773142,-73.958562,27451,Subscriber,1987,1
3,2719,2019-01-01 00:07:03.5450,2019-01-01 00:52:22.6500,504.0,1 Ave & E 16 St,40.732219,-73.981656,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,21579,Subscriber,1990,1
4,303,2019-01-01 00:07:35.9450,2019-01-01 00:12:39.5020,229.0,Great Jones St,40.727434,-73.993790,503.0,E 20 St & Park Ave,40.738274,-73.987520,35379,Subscriber,1979,1

In [4]:
# january
jan['starttime'] = pd.to_datetime(jan['starttime'])
jan['starttime'] = jan['starttime'].dt.date

jan = jan.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})

jan = jan.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])

jan.to_csv('cleaned_data/jan_citibike_data.csv')

In [5]:
# feb
feb['starttime'] = pd.to_datetime(feb['starttime'])
feb['starttime'] = feb['starttime'].dt.date


feb = feb.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})

feb = feb.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])

feb.to_csv('cleaned_data/feb_citibike_data.csv')

In [6]:
# mar
mar['starttime'] = pd.to_datetime(mar['starttime'])
mar['starttime'] = mar['starttime'].dt.date

mar = mar.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})

mar = mar.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])

mar.to_csv('cleaned_data/mar_citibike_data.csv')

In [7]:
# apr
apr['starttime'] = pd.to_datetime(apr['starttime'])
apr['starttime'] = apr['starttime'].dt.date

apr = apr.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})

apr = apr.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
apr.to_csv('cleaned_data/apr_citibike_data.csv')

In [8]:
# may
may['starttime'] = pd.to_datetime(may['starttime'])
may['starttime'] = may['starttime'].dt.date

may = may.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
may = may.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
may.to_csv('cleaned_data/may_citibike_data.csv')

In [9]:
# jun
jun['starttime'] = pd.to_datetime(jun['starttime'])
jun['starttime'] = jun['starttime'].dt.date

jun = jun.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
jun = jun.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
jun.to_csv('cleaned_data/jun_citibike_data.csv')

In [10]:
# jul
jul['starttime'] = pd.to_datetime(jul['starttime'])
jul['starttime'] = jul['starttime'].dt.date

jul = jul.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
jul = jul.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
jul.to_csv('cleaned_data/jul_citibike_data.csv')

In [11]:
# aug
aug['starttime'] = pd.to_datetime(aug['starttime'])
aug['starttime'] = aug['starttime'].dt.date

aug = aug.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
aug = aug.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
aug.to_csv('cleaned_data/aug_citibike_data.csv')

In [12]:
# sep
sep['starttime'] = pd.to_datetime(sep['starttime'])
sep['starttime'] = sep['starttime'].dt.date

sep = sep.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
sep = sep.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
sep.to_csv('cleaned_data/sep_citibike_data.csv')

In [13]:
# oct
oct['starttime'] = pd.to_datetime(oct['starttime'])
oct['starttime'] = oct['starttime'].dt.date

oct = oct.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
oct = oct.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
oct.to_csv('cleaned_data/oct_citibike_data.csv')

In [14]:
# nov
nov['starttime'] = pd.to_datetime(nov['starttime'])
nov['starttime'] = nov['starttime'].dt.date


nov = nov.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
nov = nov.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
nov.to_csv('cleaned_data/nov_citibike_data.csv')

In [15]:
# dec
dec['starttime'] = pd.to_datetime(dec['starttime'])
dec['starttime'] = dec['starttime'].dt.date

dec = dec.rename(columns={'tripduration': 'Trip Duration', 'starttime': 'Date', 'start station id': \
                                      'Start Station ID', 'start station latitude': 'Start Latitude', \
                                     'start station longitude': 'Start Longitude', 'end station id': 'End Station ID', 'start station name': \
                                     'Start Station Name', 'end station name': 'End Station Name', 'end station latitude': \
                                      'End Latitude','end station longitude': 'End Longitude', 'bikeid': 'Bike ID', 'usertype':\
                                      'User Type', 'birth year': 'Birth Year', 'gender': 'Gender'})
dec = dec.drop(columns=['Start Station ID', 'stoptime', 'End Station ID', 'End Station Name', 'End Latitude', 'End Longitude', 'Bike ID'])
dec.to_csv('cleaned_data/dec_citibike_data.csv')